/*
 Navicat Premium Data Transfer

 Source Server         : 正式152.136.224.65
 Source Server Type    : PostgreSQL
 Source Server Version : 140013 (140013)
 Source Host           : 152.136.224.65:2510
 Source Catalog        : app_gsjf_v2
 Source Schema         : vb_saas

 Target Server Type    : PostgreSQL
 Target Server Version : 140013 (140013)
 File Encoding         : 65001

 Date: 18/11/2025 15:40:18
*/


-- ----------------------------
-- Table structure for vb_openapi_columns
-- ----------------------------
DROP TABLE IF EXISTS "vb_saas"."vb_openapi_columns";
CREATE TABLE "vb_saas"."vb_openapi_columns" (
  "api_id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "column_name" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  "column_type" varchar(30) COLLATE "pg_catalog"."default",
  "is_array" bool,
  "format" varchar COLLATE "pg_catalog"."default",
  "part_id" varchar(32) COLLATE "pg_catalog"."default",
  "ordinal" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "create_at" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" bool NOT NULL DEFAULT false
)
;
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."api_id" IS '接口编号';
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."column_name" IS '列名';
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."column_type" IS '数据类型';
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."is_array" IS '数组';
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."format" IS '数据类型格式';
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."part_id" IS '分区编号';
COMMENT ON COLUMN "vb_saas"."vb_openapi_columns"."ordinal" IS '原始序号';
COMMENT ON TABLE "vb_saas"."vb_openapi_columns" IS '开放接口列定义';

-- ----------------------------
-- Primary Key structure for table vb_openapi_columns
-- ----------------------------
ALTER TABLE "vb_saas"."vb_openapi_columns" ADD CONSTRAINT "vb_openapi_columns_pkey" PRIMARY KEY ("api_id", "column_name");
